void setup() {

pinMode(13, OUTPUT); // Initialize pin 13 as digital out (LED)
Serial.begin(4800); // Open serial connection at baud rate of 4800
delay(500); // Wait half a second
Serial.println("AT"); // Sends AT command to wake up cell phone
delay(500);
Serial.println("AT+CMGF=1"); // Puts phone into SMS mode
delay(1000); // Wait a second
Serial.println("AT+CMGW=\"+15555555555\""); // Creates new message to number
delay(1000);
Serial.print("This message was generated by Arduino!"); // Message contents
delay(1000);
Serial.println(26, BYTE); // equivalent (signals end of message)
delay(1000);
Serial.println("AT+CMSS=1"); // Sends message at index of 1
delay(10000);
Serial.println("AT+CMGD=1"); // Deletes message at index of 1

}

void loop(){

digitalWrite(13, HIGH); // set the LED on
delay(250); // wait for 1/4 a second
digitalWrite(13, LOW); // set the LED off
delay(250); // wait for 1/4 a second

}
